[package]
name = "game-objects"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.30.8"
serde = { version = "1.0", features = ["derive"] }
ahash = "0.8"
rand = "0.9.2"
game-utils = { path = "../game_utils" }