[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
engine = { path = "crates/engine" }
game-objects = { path = "crates/game_objects" }
networking = { path = "crates/networking" }
physics = { path = "crates/physics" }