[package]
name = "game-world"
version = "0.1.0"
edition = "2021"


[dependencies]
game_objects = { package = "game-objects", path = "../game_objects" }
ahash = "0.8"
serde = { version = "1.0", features = ["derive"] }